apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: refreshtokens.dex.coreos.com
  labels:
    {{- include "dex-crds.labels" . | nindent 4 }}
spec:
  group: dex.coreos.com
  version: v1
  names:
    plural: refreshtokens
    singular: refreshtoken
    kind: RefreshToken
