{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "mlrun.fullname" . }}
  labels:
{{ include "mlrun.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "mlrun.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "mlrun.serviceAccountName" . }}
{{- end -}}
