{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
{{ include "dex.labels" . | indent 4 }}
  name: {{ template "dex.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["dex.coreos.com"] # API group created by dex
  resources: ["*"]
  verbs: ["*"]
{{- if or .Values.certs.grpc.create .Values.certs.web.create }}
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["create", "delete"]
{{- end -}}
{{- end -}}
